#!/bin/bash
# ~/ipp/gtk-tut-python
# mkdir ~/ipp/gtk-tut-python
cat << EOF | tee ~/ipp/gtk-tut-python/README >/dev/null
This should be sufficient to create rock solid fingerprint reader GUI
as well as to map a few upcoming projects.
Since I am following the tutorial top down starting with chapter 1,
these files contain mainly the tutorial code which had been caught by
the deprecation warning system and rewritten or is in the process of being rewritten
using the recommended widget in sort of opportunistic way.

EOF

cd ~/ipp/gtk-tut-python
git add README
# git add bluezchat.glade
# git add bluezchat.py
# git add chaincolorselector.py
# git add magick_jpeg2png.py
# git add progressbar.py
# git add pygtksourceview-widget.py
# git add rangewidgets.py
# git add tinygecko.py
# git add togglebutton.py
# git add tooltip.py
# git add wheelbarrow.py
# git add browser.py
# git add gnome-menus-ls.py
# git add inspector.py
# git add notebook.py
# git add toolbar.py
# git add viewXPM.py
# git add gitsetup-ipp-gtktut
git add interactivefilesel.py
git commit -a -m 'add python gtk tutorial directory and contents'
git push
